# Generated by Django 4.2 on 2024-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default='0000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.SmallIntegerField(default='9'),
        ),
    ]
