# Generated by Django 4.2 on 2024-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_student_gpa_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default='100', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='osis',
            field=models.IntegerField(default='0000000', unique=True),
        ),
    ]
